### ISSUE TITLE
Error Enabling XBOX Live Creators Program

### ISSUE THREAD

**Issue by stonstad** [Microsoft/xbox-live-api#113]
Enabling an app for XBOX Live Creators Program is failing in the developer portal.  Here's my original question posted on StackOverflow which includes a screenshot of the behavior and a stacktrace of the javascript errors.

http://stackoverflow.com/questions/43024323/error-enabling-xbox-live-creators-program

**Comment by stonstad** [comment]
I can confirm that Creators Program enablement works for a newly created UWP app.  My existing one (18284ShaunTonstad.StellarConquest) must be bugged somehow.  Is there a point of contact I might try reaching out to for this behavior?

**Comment by jasonsandlin** [comment]
Thanks for the bug report.  The issue should be fixed now. Please try again and let us know

**Comment by stonstad** [comment]
Works now, thank you!
