### ISSUE TITLE
Restore failed for Microsoft.Xbox.Live.SDK.WinRT.UWP 2017.4.20170412.1 NuGet package

### ISSUE THREAD

**Issue by Myfreedom614** [Microsoft/xbox-live-api#129]
1. Create a new UWP app in VS2015
2. Install Microsoft.Xbox.Live.SDK.WinRT.UWP 2017.4.20170412.1
3. Restore failed

**Comment by adityatMS** [comment]
We are currently looking into this. Will update the thread as I have more information.

**Comment by jasonsandlin** [comment]
Thanks for the bug report -- we posted newer version with this issue fixed.  Please try again with version 2017.4.20170413.1

**Comment by Myfreedom614** [comment]
@adityatMS @jaestevan Thanks, it works now:)
