### ISSUE TITLE
GetLeaderboardForSocialGroupAsync() fails for Favorite category

### ISSUE THREAD

**Issue by pnp2084** [Microsoft/xbox-live-api#134]
Calling GetLeaderboardForSocialGroupAsync() with the SocialGroupConstants::Favorite category fails because the Xbox Live SDK (UWP) code passes the text Favorite in the URL instead of favorite.

leaderboard_service::get_leaderboard_for_social_group_internal() should do something like:

```
 if (utils::str_icmp(socialGroup, _T("Favorite")) == 0)
 {
     group = _T("favorite");
 }
```

**Comment by adityatMS** [comment]
Casing on the URL shouldn't matter. The correct fix is to change social_group_constants::favorite() to return _T("Favorite") instead of _T("Favorites"). I'll send a PR shortly with a fix.

**Comment by adityatMS** [comment]
Sorry for the delay in getting back to you. We've decided to fix this on the service instead where the service will understand both 'Favorite' and 'Favorites'. I will update the thread when a fix is deployed. In the meantime, you can change the constant to 'Favorites' to unblock yourself.

**Comment by adityatMS** [comment]
The fix for the issue was deployed yesterday. Please let us know if you are still seeing any issues.
