### ISSUE TITLE
Building to UWP error

### ISSUE THREAD

**Issue by CrohnsAndMe** [Microsoft/xbox-live-api#163]
Hey these are the errors i am getting

http://imgur.com/a/RLCng

I do not understand what is causing this. I imported the plugin from the github page and when building to windows 10 UWP i get this build error

**Comment by jasonsandlin** [comment]
In Unity, when you go to "Build Settings" what is the "UWP SDK" version you are using?

**Comment by jasonsandlin** [comment]
Please re-open this issue if your still having trouble
