### ISSUE TITLE
pplx::create_task does not compile with winrt::Windows::Foundation::IAsyncOperation return type

### ISSUE THREAD

**Issue by jorgenhs** [Microsoft/xbox-live-api#179]
pplx::create_task does not support cppwinrt IAsyncOperation types when programming with the XDK. The following code does *not* compile (the return type of pplx::create_task resolves to _BadResultType):

  typedef winrt::SomeXDKResultType TokenResult;
  TokenResult tokenResult = nullptr;
  pplx::task<TokenResult> t = pplx::create_task(firstUser.SomeXDKFunction(TEXT("POST"), *uri, TEXT("")))
  .then([&](pplx::task<TokenResult> tokenTask) { ...

The following code compiles, but requires regular winrt:

  typedef SomeXDKResultType^ TokenResult;
  TokenResult tokenResult;
  pplx::task<TokenResult> t = pplx::create_task(firstUser->SomeXDKFunction(ref new Platform::String(TEXT("POST")), ref new Platform::String(*uri), ref new Platform::String(TEXT(""))))
  .then([&](pplx::task<TokenResult> tokenTask) {...

Interop with cppwinrt would be quite useful in many Xbox Live programming scenarios.

**Comment by jasonsandlin** [comment]
Understood, this is on our backlog.  We plan to make changes so our C++ API so it can compile without /ZW (aka without using C++/CX, aka without hats) to fix this issue.  But we may not get to this soon. 
Can you work around this issue for a few months?

**Comment by jorgenhs** [comment]
Thanks for the update.

We can work around it, at a cost of some elegance. 😊

Fra: Jason Sandlin<mailto:notifications@github.com>
Sendt: fredag 26. mai 2017 kl. 12.15
Til: Microsoft/xbox-live-api<mailto:xbox-live-api@noreply.github.com>
Kopi: Jørgen Havsberg Seland<mailto:jorgenhs@funcom.com>; Author<mailto:author@noreply.github.com>
Emne: Re: [Microsoft/xbox-live-api] pplx::create_task does not compile with winrt::Windows::Foundation::IAsyncOperation return type (#179)


Understood, this is on our backlog. We plan to make changes so our C++ API so it can compile without /ZW (aka without using C++/CX, aka without hats) to fix this issue. But we may not get to this soon.
Can you work around this issue for a few months?

**Comment by crautou** [comment]
Hello,
Any news on this ? is there a simple workaround at this date ?

**Comment by jameslen-atg** [comment]
You have 2 options here:
1) You can use the C++/WinRT projections of XSAPI and those work without /Zw
2) If you stick with the C++ version of XSAPI you will need to keep /Zw due to XSAPI using WinRT types (with hats) under to hood and you will have to switch your platform code away from create_task and use coroutines instead. (https://www.youtube.com/watch?v=v0SjumbIips)

**Comment by crautou** [comment]
Yes, I'm in the first case, and it works ok, but I still can't use the create_task in this scenario : it won't compile if I pass a winrt::Windows::Foundation::IAsyncOperation to it (with November XDK).

**Comment by jameslen-atg** [comment]
Unfortunately, then the change to C++/WinRT that removes support with pplx was brought into the XDK and you will have to move to coroutines.

**Comment by crautou** [comment]
Ok thank you for your help

**Comment by jasonsandlin** [comment]
In additional to what James says above, we are addressing this in our new C API which doesn't require /Zw to use.
