### ISSUE TITLE
Cannot Update Xbox Live Creators Program Leaderboard

### ISSUE THREAD

**Issue by r2d2Proton** [Microsoft/xbox-live-api#203]
Hello All.

I'm having difficulty updating my Leaderboard on the Xbox Live Creators Program using the Unreal Engine 4 (UE4) with UWP.

Can you confirm if my approach is correct:

    IOnlineSubsystem* oss = IOnlineSubsystem::Get();

    if (oss != nullptr)
    {
        IOnlineEvents* events = oss->GetEventsInterface().Get();

        if (events != nullptr)
        {
            FOnlineEventParms ep;
            ep.Add(FName(TEXT("HighScore")), levelScore->GetTotalScore());
            events->TriggerEvent(*playerId, TEXT("OceanWave"), ep);
        }
    }

If my setup is correct, whould I see it in the GameHub? How do I know it's working?

**Comment by jasonsandlin** [comment]
The Xbox Live Creators Program is an open program for developers using any game engine that supports the Universal Windows Platform (UWP). For specific engine details around features and levels of support, you should reach out to the game engine provider directly.
