### ISSUE TITLE
get_response_with_auth wrong on cpp?

### ISSUE THREAD

**Issue by adrianhirst** [Microsoft/xbox-live-api#204]
Hi,

This method seems wrong:-

`   virtual pplx::task<std::shared_ptr<http_call_response>> get_response_with_auth(
        _In_ const std::shared_ptr<XBOX_LIVE_NAMESPACE::user_context>& userContext,
        _In_ http_call_response_body_type httpCallResponseBodyType = http_call_response_body_type::json_body,
        _In_ bool allUsersAuthRequired = false
        ) = 0;
`
It takes as a parameter a user_context that is only forward declared in types.h, therefore you can't call std::make_shared with an xbox_live_user.

Am I missing something?

The WinRT version allows you to pass a User and works fine.

Thanks

**Comment by jasonsandlin** [comment]
https://github.com/Microsoft/xbox-live-api/pull/206

should fix it and will be in soon

**Comment by adrianhirst** [comment]
Awesome, thanks for the fix.

**Comment by adrianhirst** [comment]
Actually I think its broken with many errors like this:-

`
1>e:\xbox-live-api-master\source\shared\http_call_impl.h(263): error C3668: 'xbox::services::http_call_impl::get_response_with_auth': method with override specifier 'override' did not override any base class methods (compiling source file E:\xbox-live-api-master\Build\Microsoft.Xbox.Services.140.UWP.Cpp\..\..\Source\Services\Achievements\achievement.cpp)
`

I'm compiling in 2015 update 3

**Comment by jasonsandlin** [comment]
Oops, fixing incoming

**Comment by jasonsandlin** [comment]
Fixed now https://github.com/Microsoft/xbox-live-api/pull/207
