### ISSUE TITLE
StatisticManager::AddLocalUser crashes when a user is added twice

### ISSUE THREAD

**Issue by r2d2Proton** [Microsoft/xbox-live-api#215]
Is there a C++ example that uses the Statistics namespace for writing to and reading from the xbox live services (stats/leaderboard information)?

How do I check if a user was already added to the StatisticManager? If I call AddLocalUser more than once for the same user the SDK crashes.

**Comment by jasonsandlin** [comment]
If your using our WinRT API and calling from C++/CX or C#, AddLocalUser throws an exception that says user already added.  

If your using our C++ API, it returns an error: 
https://github.com/Microsoft/xbox-live-api/blob/master/Source/Services/Stats/Manager/stats_manager_impl.cpp#L101

You can ignore this exception/error if you need to.  It's best to add the user when a user is added to the game and remove it when a user is removed from the game.  

btw, if you are using C++/CX be sure to do proper error handling by catching the exceptions:
https://docs.microsoft.com/en-us/windows/uwp/xbox-live/using-xbox-live/error-handling/error-handling-winrt

There isn't a C++ sample yet but its on our backlog

**Comment by jasonsandlin** [comment]
Feel free to re-open if you have other issues
