### ISSUE TITLE
XboxLiveUser Behavior on PC vs XBox

### ISSUE THREAD

**Issue by stonstad** [Microsoft/xbox-live-api#220]
I am running into inconsistent behavior with this code on XBox vs PC:

```
XboxLiveUser user = new XboxLiveUser();
SignInResult result = await user.SignInAsync();
```

On PC this always works.  On XBOX this works if I create a new UWP store app and register and enable XBOX Services.  For a legacy Store app that is unpublished it acts like a no-op.  On the XBox the XboxLiveUser instance does not have any data populated and the SignInAsync command doesn't do anything.  No errors either.  

To get this to work on XBox I just have to change service configuration to my newly created app ... but I'd like to add Xbox Live to my existing (but not published) app. 

Not sure how to proceed or whether this might be a bug or data issue relating to an older app store submission?

**Comment by stonstad** [comment]
I am wondering if I posted this question to the wrong repository.  Should I post it here? https://github.com/Microsoft/xbox-live-api-csharp/issues?

Thanks

**Comment by jasonsandlin** [comment]
This is the right spot.  We're looking into this and will get back to you

**Comment by stonstad** [comment]
Thanks, Jason.  Would it help to send you my service configuration?  My email is tonstad (at) outlook dot com.

**Comment by jasonsandlin** [comment]
Yeah, I'll email you

**Comment by jasonsandlin** [comment]
Working with you over email to figure out what's going with your service config
