### ISSUE TITLE
Caching Stat Issue

### ISSUE THREAD

**Issue by r2d2Proton** [Microsoft/xbox-live-api#233]
Even if the stat is deleted from Dev Center, and publish, the stat remains relentlessly on my local machine. How do I clear the cache?
Is there a setting to ensure updates are monitored more frequently.

**Comment by jasonsandlin** [comment]
Try calling:
https://github.com/Microsoft/xbox-live-api/blob/master/Source/Services/Stats/Manager/WinRT/StatisticManager_WinRT.h#L132
or
https://github.com/Microsoft/xbox-live-api/blob/master/Include/xsapi/stats_manager.h#L311

And flush that to service.

**Comment by jasonsandlin** [comment]
Please reopen this isn't working
