### ISSUE TITLE
Updating Stat with Lesser Value Problem

### ISSUE THREAD

**Issue by r2d2Proton** [Microsoft/xbox-live-api#234]
I cannot update a stat with a lesser value:

![statcacheproblem 01](https://user-images.githubusercontent.com/4054178/28641186-8e019aba-720b-11e7-922c-272ecf5629d7.jpg)

**Comment by jasonsandlin** [comment]
Our docs aren't yet clear about how this work.  We will fix the docs soon.
Global leaderboards currently remember the highest (or lowest, depending on config) value you set, but this may change in the future.
Therefore we recommend the value of the stats always either increases or decreases vs doing both

**Comment by r2d2Proton** [comment]
Is there a way to "reset" stats on Dev Center? For example, I'm testing and I want to reset what I have.

It appears to me that I would first need to delete all my stats pragmatically (https://github.com/Microsoft/xbox-live-api/blob/master/Source/Services/Stats/Manager/WinRT/StatisticManager_WinRT.h#L132), and then recreate them on Dev Center. Is this the correct approach?

Is there any way to create the stats on Dev Center pragmatically?

**Comment by jasonsandlin** [comment]
For now, delete them all pragmatically.  No need to delete or recreate them on Dev Center as that just configures how you view stats (either as a Feature Stat, or as a Leaderboard).

**Comment by jasonsandlin** [comment]
Please reopen this isn't working
