### ISSUE TITLE
Both DisplayName and StatisticName are null

### ISSUE THREAD

**Issue by r2d2Proton** [Microsoft/xbox-live-api#237]
As mentioned previously, the DisplayName and StatisticName are returned as null. I tried accessing the value from the Leaderboard Sample too and encountered the same problem for display name. There didn't appear to be a way to access the stat name from the sample. Please see the images below. I may be able to debug this with the Sample since it includes the DLL too :)

![displaynamestatname 01a](https://user-images.githubusercontent.com/4054178/28678289-3e567466-72ad-11e7-81a1-4b21b35197dc.jpg)

![displaynamestatname 01b](https://user-images.githubusercontent.com/4054178/28678293-434e4d0e-72ad-11e7-8abf-46969a60f6ff.jpg)

![displaynamestatname 02](https://user-images.githubusercontent.com/4054178/28678358-6983b766-72ad-11e7-931a-fb17bac0a6be.jpg)

![displaynamestatname 03](https://user-images.githubusercontent.com/4054178/28678366-6e8c6e6a-72ad-11e7-984f-2c0067646b0f.jpg)

![displaynamestatname 04](https://user-images.githubusercontent.com/4054178/28678376-72c58b7e-72ad-11e7-8938-e93641d468d5.jpg)

**Comment by jasonsandlin** [comment]
I'll debug and get back to you

**Comment by jasonsandlin** [comment]
I can confirm this is a bug.  I'll get a fix for this soon

**Comment by r2d2Proton** [comment]
Thank you Jason :)

**Comment by jasonsandlin** [comment]
Ok, this should be fixed now:

https://github.com/Microsoft/xbox-live-api/commit/add8f2fae3ed890611eed537bc555ade9d630f26

I updated that C++/CX test app to log these values.
