### ISSUE TITLE
Feature Request: Support for building for Android

### ISSUE THREAD

**Issue by zhuowei** [Microsoft/xbox-live-api#239]
There's currently no instructions for building the Xbox Live API for Android development. The code [seems to have support](https://github.com/Microsoft/xbox-live-api/search?utf8=%E2%9C%93&q=XSAPI_A), and libHttpClient already works on Android, so it would be nice to add an Android NDK/CMake/Gradle compatible build system.

**Comment by jasonsandlin** [comment]
We don't yet have public support for Xbox Live on iOS or Android.  

For developers in the Xbox Live Creators Program, you can submit a new idea or vote on existing idea at our Xbox Live Creators Program User Voice at https://xbox.uservoice.com/forums/363186--new-ideas/category/196261-xbox-live-creators-program

btw do note that libHttpClient has a goal to support iOS & Android but it doesn't yet.  However we're currently using cpprestsdk (not yet libHttpClient) does have public support for both iOS & Android
