### ISSUE TITLE
Compile Error: multiplayer_session_constants.cpp

### ISSUE THREAD

**Issue by r2d2Proton** [Microsoft/xbox-live-api#242]
The transform of targetLocationKey to lower is causing the compiler to complain:

1>multiplayer_session_constants.cpp
1>e:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include\algorithm(946): error C2220: warning treated as error - no 'object' file generated
1>e:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include\algorithm(961): note: see reference to function template instantiation '_OutIt std::_Transform_unchecked<wchar_t*,wchar_t*,int(__cdecl *)(int)>(_InIt,_InIt,_OutIt,_Fn1 &)' being compiled
1>        with
1>        [
1>            _OutIt=wchar_t *,
1>            _InIt=wchar_t *,
1>            _Fn1=int (__cdecl *)(int)
1>        ]
1>e:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include\algorithm(971): note: see reference to function template instantiation '_OutIt std::_Transform_no_deprecate<_InIt,_OutIt,int(__cdecl *)(int)>(_InIt,_InIt,_OutIt,_Fn1 &)' being compiled
1>        with
1>        [
1>            _OutIt=std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
1>            _InIt=std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
1>            _Fn1=int (__cdecl *)(int)
1>        ]
1>e:\ueuwp\xbox-live-api\source\services\multiplayer\multiplayer_session_constants.cpp(496): note: see reference to function template instantiation '_OutIt std::transform<std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,int(__cdecl *)(int)>(_InIt,_InIt,_OutIt,_Fn1)' being compiled
1>        with
1>        [
1>            _OutIt=std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
1>            _InIt=std::_String_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
1>            _Fn1=int (__cdecl *)(int)
1>        ]
1>e:\program files\microsoft visual studio\2017\community\vc\tools\msvc\14.10.25017\include\algorithm(946): warning C4244: '=': conversion from 'int' to 'wchar_t', possible loss of data
1>Done building project "Microsoft.Xbox.Services.140.UWP.WinRT.vcxproj" -- FAILED.

I modified the transform some to get around this error but not sure how it would apply globally:

        std::locale loc;
        std::transform(
            targetLocationKey.begin(),
            targetLocationKey.end(),
            targetLocationKey.begin(),
            [loc](wchar_t c) -> wchar_t { return std::tolower(c, loc); });

If the original does compile then maybe I'm missing an include or some other setting.

**Comment by jasonsandlin** [comment]
We aren't seeing that error, but we are using VS2015 to build this project not VS2017.  Our VS2017 projects are for the C++ API (not WinRT API) so we'll have to try to repro by building this project with VS2017.

**Comment by jasonsandlin** [comment]
Hmm, I opened the project
C:\git\forks\xbox-live-api\Build\Microsoft.Xbox.Services.140.UWP.WinRT\Microsoft.Xbox.Services.140.UWP.WinRT.sln
 and rebuilt with VS2017 and didn't see any errors. 

Here's the version I'm using:
Microsoft Visual Studio Community 2017 
Version 15.2 (26430.16) Release

and the bottom of the build log:

2>   Creating library C:\git\forks\xbox-live-api\Build\Microsoft.Xbox.Services.140.UWP.WinRT\..\..\Binaries\Debug\x64\Microsoft.Xbox.Services.140.UWP.WinRT\Microsoft.Xbox.Services.lib and object C:\git\forks\xbox-live-api\Build\Microsoft.Xbox.Services.140.UWP.WinRT\..\..\Binaries\Debug\x64\Microsoft.Xbox.Services.140.UWP.WinRT\Microsoft.Xbox.Services.exp
2>Microsoft.Xbox.Services.140.UWP.WinRT.vcxproj -> C:\git\forks\xbox-live-api\Build\Microsoft.Xbox.Services.140.UWP.WinRT\..\..\Binaries\Debug\x64\Microsoft.Xbox.Services.140.UWP.WinRT\Microsoft.Xbox.Services.dll
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by r2d2Proton** [comment]
Okay, my Visual Studio is a slight build behind yours but would that make a difference:
![vs ver](https://user-images.githubusercontent.com/4054178/28847242-bb8fde32-76cb-11e7-8ac4-79fa42469b7f.jpg)

**Comment by r2d2Proton** [comment]
May I ask what actions did you take when you opened the solution using VS2017? Did you upgrade?

**Comment by jasonsandlin** [comment]
No I didn't upgrade.  I have the v140 support installed so it didn't ask me to upgrade.

**Comment by r2d2Proton** [comment]
Do you want me to try the upgrade path again?

**Comment by jasonsandlin** [comment]
If you figure out how I can reproduce the issue, do let me know so we can squash the bugs now & for future :)

**Comment by r2d2Proton** [comment]
Yes, I'm trying to provide the specifics.

**Comment by jasonsandlin** [comment]
Feel free to submit a pull request to fix the error your seeing as we can't reproduce.  If you figure out what is causing this build error let us know.  Thanks
