### ISSUE TITLE
multiplayer_client_manager::match_client crashes when latest_pending_read() is null

### ISSUE THREAD

**Issue by Scraft** [Microsoft/xbox-live-api#252]
We have a Unity game, in certain circumstances it'll cancel the matchmaking/match when it isn't even in an online match/matchmaking session - we could further improve our logic/flow, but either way, we should not get a crash in this scenario. The following fixes this:

multiplayer_client_manager.cpp

    std::shared_ptr<multiplayer_match_client>
    multiplayer_client_manager::match_client()
    {
        return latest_pending_read()->match_client();
    }

change to:

    std::shared_ptr<multiplayer_match_client>
    multiplayer_client_manager::match_client()
    {
        if (latest_pending_read() == nullptr)
	    	return nullptr;

        return latest_pending_read()->match_client();
    }

**Comment by jasonsandlin** [comment]
Thanks for the report.  Do you want to send a pull request?

**Comment by jasonsandlin** [comment]
Fixed this and other related issues here: https://github.com/Microsoft/xbox-live-api/pull/257
