### ISSUE TITLE
SignInAsync Inconsistency between Xbox and UWP.

### ISSUE THREAD

**Issue by Sedge84** [Microsoft/xbox-live-api#267]
Hi,

I have noticed an inconsistency between XB1 and UWP when it comes to the UI showing when calling SignInAsync(). The UI will show every time when called on the XB1 but it will only show if the user is not signed in on UWP. 

When the user switches user via the Main Menu we kick back to the title screen then call SignInAsync() where we expect it to open the UI to allow the user to switch to a different user. This works as expected on XB1.

Maybe I am missing something or should call something to force a log out?

Thanks,
Phil

**Comment by jasonsandlin** [comment]
Can you copy/paste your signin code so we can see how you are calling the SignInAync() API?

Also is your UWP app a multi-user application: https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/multi-user-applications?

**Comment by Sedge84** [comment]
It’s via UE4, It’s for crackdown 3.

I can send you the sample code when I am on my pc.

I will have to take a look at the setup for the multi user, is that a app
mainfiest thing or XDP/UDC thing.

Thanks,
Phil

**Comment by jasonsandlin** [comment]
Ah, in that case email me at jasonsa@microsoft.com and we will take offline
