### ISSUE TITLE
Is compiling with XSAPI_SERVER officially supported?

### ISSUE THREAD

**Issue by StephenE** [Microsoft/xbox-live-api#274]
We'd like to use XSAPI on our Xbox Live Compute hosted game service, and I can see there is a 'XSAPI_SERVER' define - but I can't find any documentation about this define and I was wondering if it's a supported option currently?

I've not been able to find the implementation of xbox_live_server::signin, so it feels like there's something missing from the depot?

**Comment by jicailiu** [comment]
We only had some very early stage experiment, but server version of xsapi is not supported and we current don't have plan to support that.
