### ISSUE TITLE
WinRT Nuget packages do not work properly when used with UWP 6.0.1.

### ISSUE THREAD

**Issue by Petezah** [Microsoft/xbox-live-api#278]
Repro: 
* Create a new Blank project (C#)
* Ensure UWP packages are upgraded to latest (6.0.1)
* Add Microsoft.Xbox.Live.SDK.WinRT.UWP

Observe:
* No Microsoft.Xbox.Services.winmd appears in the References node.
* Intellisense does not find anything in Microsoft.Xbox namespace.

Then (workaround):
* Downgrade UWP packages to 5.4.1
* Close and reopen solution

Observe:
* Microsoft.Xbox.Services.winmd does appear in the References node.
* Intellisense finds everything under Microsoft.Xbox as expected.

I also noticed that I can get everything to work properly if I build the xbox-live-api project from source with VS2017.  This also required me to upgrade the build tools in the vcxproj to 2017 for both the Xbox Live services project and the dependency cpprestsdk.

**Comment by jasonsandlin** [comment]
Which version of Microsoft.Xbox.Live.SDK.WinRT.UWP are you using from https://www.nuget.org/packages/Microsoft.Xbox.Live.SDK.WinRT.UWP/?  

I don't see a v6.0.1 or v5.4.1 there so not sure what version you are referring to.

**Comment by Petezah** [comment]
Sorry I was not clear.  I am using:
Microsoft.Xbox.Live.SDK.WinRT.UWP version "v2017.8.20170829.1".
I was referring to:
Microsoft.NETCore.UniversalWindowsPlatform version "6.0.1" (and subsequently version "5.4.1").  The nuget packages for the Universal Windows Platform itself.

**Comment by jasonsandlin** [comment]
Ah, thanks for the bug report.  We'll have to investigate the best way to fix this

**Comment by jasonsandlin** [comment]
I was able to repo this back when this was reported, but now that I'm looking into it I can no longer reproduce it, even on a fresh clean machine with just VS2017 installed.  I suspect it was a bug that got fixed in a Visual Studio 2017 patch.  Try upgrading to Visual Studio 2017 v15.4.5 and try again.  Thanks

**Comment by Petezah** [comment]
I can confirm, it seems to be fixed after upgrading to v15.4.5.

**Comment by jasonsandlin** [comment]
Great :)
