### ISSUE TITLE
SetStatistics adds revision number that exceeds Integer and results in a 400 Error

### ISSUE THREAD

**Issue by tecraveiro** [Microsoft/xbox-live-api#288]
Hi, I'm using the 1708 QFE1 release and trying to read and write stats.

I am getting 500 code internal server errors on statsread and a 400 code bad request error on statswrite, the latter because SetStatistics automatically adds a revision number that exceeds Integer which the server doesn't like:

![statsupdaterevisionnumberintegeroverflow](https://user-images.githubusercontent.com/5417392/33382852-bea31d44-d519-11e7-8d53-6226717f78aa.JPG)

I am not sure if the statsread internal server error is related (might be a Dev Center / sandbox issue) but I have stats configured in Dev Center and  am using the right sandbox but they cannot be read through GetStatistic or GetStatisticNames. See 500 error below:

![statsread500error](https://user-images.githubusercontent.com/5417392/33382878-d1cc72f8-d519-11e7-8e24-3efa9680bba0.JPG)

If this has been fixed by commit 
https://github.com/Microsoft/xbox-live-api/commit/086a63d51330cd98c8b9c15846756efd07644c20
then can you please put out a new release? It's been almost three months since the last one.

Thanks in advance!

**Comment by jasonsandlin** [comment]
Thanks for the bug report.  We actually already have this fix in our master branch.  We'll be pushing out a 1711 release very soon which will fix this.

**Comment by jasonsandlin** [comment]
1711 is now released with this fix :)
