### ISSUE TITLE
What features of WinRT API are implemented?

### ISSUE THREAD

**Issue by Vesemirek** [Microsoft/xbox-live-api#311]
Hello!

I've tried to retrieve anything from XBOX Live Services for about **2 weeks.** 

**I managed to:**
- log in my test account 
- retrieve basic information about the user
- create context for the user
- get the list of achievements for the game

**I didn't manage to:**
- set any award for the user
- set or get any statistic of the user
- report any score or request any score for the user
- send user presence

**Or anything at all.**

Tried **everything**, requesting every possible instances, services or anything at all I could find in the Xbox Live WinRT SDK documentation. Everything on the DevCenter is assured to be set up properly, same with the application (store association, xboxservices.config, storeKeys and so on).

Is the more than a half of the content of Xbox Live even implemented in the API?

Or should I immediately start to recall my knowledge about C++ and start from scratch without it?

Or maybe there are more docs, that I'm not aware of?

**Comment by Vesemirek** [comment]
**Additional Information:**
- developing UWP app for Windows Store
- using C# to develop (that's why I choose WinRT version)
- project based on Unity 2017.3
- targeting ID@XBOX with features such as Achievements 2017

**Comment by XboxLiveForum** [comment]
Hi Vesemirek,

In order for us to better assist here, could you please provide the following information:
1. Just to clarify, are you already registered with the ID@Xbox program?
2. What version of Xbox Live are you using?
3. What IDE are you using and what version?

Thanks!

**Comment by jasonsandlin** [comment]
Hmm, all the Xbox Live services a game can call are implemented in the WinRT API.  A number of big game studios have shipped using the WinRT API.

There's docs about how to use Unity and the WinRT API at:
https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-partner/partner-add-xbox-live-to-unity-uwp

There's a few Unity samples using the WinRT API at:

https://github.com/Microsoft/xbox-live-samples/tree/master/Samples/ID%40XboxSDK/Social/Unity
https://github.com/Microsoft/xbox-live-samples/tree/master/Samples/ID%40XboxSDK/GameSave/Unity
https://github.com/Microsoft/xbox-live-samples/tree/master/Samples/ID%40XboxSDK/DataPlatform2013/Achievements2013/Unity

See the readme for how to run them.  For example:
https://github.com/Microsoft/xbox-live-samples/blob/master/Samples/ID%40XboxSDK/Social/Unity/Readme.md

**Comment by Vesemirek** [comment]
Hello,  thanks for an aswer.

**1. ID@XBOX** 
Yes and I plan to be prepared for every feature that this program supports in opposition to Creators Program and of course basic features that are supported in CP and ID@XBOX.

**2. Xbox Live** 
Do you mean which structure (2013 or 2017) I'm targeting? If so, as im registered in ID@XBOX I'm trying to target Stats 2017 and Achievements 2017 and of course features such as rich presence. 
If you're talking about XSAPI, it's the latest avaible unitypackage (1711). 
Xbox version on my PC is 36.36.12003.00000.

**3. About IDE:**
I tried on every update of VS2015 Community and VS2017 Community with Unity Tools. Also tried building in Unity 5.6.4p4, Unity 2017.2.0f3 and Unity 2017.3.1f1, both using IL2CPP and NET builds.
Some builds connected, some crashed during compiling, some messed up with UnityLinker, SerializationWeaver (even empty builds), so after trying everything I stumbled upon that one moment when I tested it on very old environment on the other PC with another test account and from my entire code I managed to score an achievement.

So I'm currently running on VS2015 Update 3 and building on Unity 5.6.4p4 with Windows 10 SDK version 10.0.14393.0 IL2CPP build, because that's the only option that worked somehow with the achievement system.

As it may seem for now, it can be an issue with Unity and/or the IDE itself or that specific test account, so sorry about questioning the API implementation. But still, I did not manage to do anything else, except managing to award test account with the achievement on that one proper environment setup. 

About the docs, I've read the entire Xbox Live guidelines and WinRT docs, every sample, even strict C++ headers to understand what's happening, even if I'm more familiar with C#. But thank you for providing those links, they may be useful for others reading this issue.

**Comment by Vesemirek** [comment]
If you need any examples of my implementation, current version of the tools or what I've tried to do, contact me ;) (fiddler feedback messages, scripts and so on).

**Comment by Vesemirek** [comment]
Using most of the commands with await keyword caused those issues. Sorry for bothering you, #blameTheIDE

**Comment by allancozart** [comment]
All of the unity samples links are broken. @jasonsandlin can you provide the new locations?

**Comment by jasonsandlin** [comment]
The 3 unity samples that use the XSAPI WinRT API are here:

https://github.com/microsoft/xbox-live-samples/tree/master/ID%40XboxSDK/GameSave/Unity https://github.com/microsoft/xbox-live-samples/tree/master/ID%40XboxSDK/DataPlatform2013/Achievements2013/Unity https://github.com/microsoft/xbox-live-samples/tree/master/ID%40XboxSDK/Social/Unity

**Comment by allancozart** [comment]
Thanks @jasonsandlin !

Do you know if there's anything like the unity xbox live plugin found here, available for ID@Xbox UWP games https://github.com/Microsoft/xbox-live-unity-plugin

Also will that plugin work for ID games if you add achievements ?

**Comment by jasonsandlin** [comment]
Do not use https://github.com/Microsoft/xbox-live-unity-plugin for ID@Xbox titles.  It doesn't have achievements and a bunch of other features.  Its only designed for Creators.
