### ISSUE TITLE
SwitchAccountAsync function is missing

### ISSUE THREAD

**Issue by michaelarts** [Microsoft/xbox-live-api#324]
Hi, I'm an ID@Xbox developer using C# and MonoGame to program a UWP Xbox One game. I'm using the latest version of XSAPI.UWP from NuGet. There is a requirement that we need an option on the main menu to let the player switch profiles... I see no actual way to do this in XSAPI. If you look in the CHM documentation there is a function in XboxLiveUser called SwitchAccountAsync() but when trying to use this function in XSAPI it's nonexistent.

I've posted a thread here detailing how I'm currently trying to switch users but I can't get anything working: https://social.msdn.microsoft.com/Forums/en-US/31835e63-c766-4d7a-8588-f2fd2f1f693b/uwp-changing-users-during-game?forum=xboxlivedev

Microsoft told me via email that UWP games are not exempt from this requirement, so either I'm not seeing how to do this or the functions I need are missing.

Would really appreciate some assistance!

Thanks,

Michael

**Comment by jplafonta** [comment]
Hello @michaelarts,

This is not supported at this time.  You can switch users using the windows Xbox app but there is not currently a way to do this from within your game.

**Comment by michaelarts** [comment]
Thanks, for anyone who reads this in the future: the way to switch users is to use the UserPicker class. I've posted my code here: https://gist.github.com/michaelarts/2ada67de3ca4295b1ea57df00fd230ca
