### ISSUE TITLE
Inconsistency between GetLeaderboard and GetSocialLeaderboard in Statistics Manager

### ISSUE THREAD

**Issue by pjcard** [Microsoft/xbox-live-api#342]
It seems like `GetSocialLeaderboard` is returning the wrong value for StatisticName. If I call `GetLeaderboard`, it correctly returns the name of the statistic itself, but if I call `GetSocialLeaderboard` it incorrectly returns the display name instead.

Here is my setup:

![image](https://user-images.githubusercontent.com/8281121/38738089-1fc8979c-3f29-11e8-9e6f-b74229d2e797.png)

This is the result when I call:

`GetSocialLeaderboard( <myuser>, "DistanceTravelled", ... );`

![image](https://user-images.githubusercontent.com/8281121/38737750-1b014dfe-3f28-11e8-8ee2-2598a3c52732.png)

This is the result when I call:

`GetLeaderboard( <myuser>, "DistanceTravelled", ... );`

![image](https://user-images.githubusercontent.com/8281121/38738286-a8c7fe66-3f29-11e8-9cb2-3274541c9991.png)

This is compounding https://github.com/Microsoft/xbox-live-api/issues/341

**Comment by jasonsandlin** [comment]
Definitely a bug somewhere.  Can you email a fiddler of this call to jasonsa@microsoft.com and I'll help track this down.  Thanks

**Comment by pjcard** [comment]
Thanks James, I've send you an email with that trace in.

**Comment by jasonsandlin** [comment]
Feel free to email me if you still are hitting issues with this
