### ISSUE TITLE
Can't load achievements from WinRT JS API

### ISSUE THREAD

**Issue by AshleyScirra** [Microsoft/xbox-live-api#348]
I am trying to implement support for Achievements in Construct 2 and Construct 3 using the WinRT JS API (which unfortunately does not appear to be documented anywhere, so I'm mainly guessing calls from code in this repo and using the debugger). I have a title set up and I have been told it has had ID@Xbox features enabled. I can see a section to set up achievements in the dev center, so I've added two.

Calling `xboxLiveContext.achievementService.updateAchievementAsync(xboxUserId, achievementId, 100)` fails with "The parameter is incorrect.". I am certain `xboxUserId` is correct, since it works for other API calls. The `achievementId` apparently ought to be a string, even though the dev center lists achievement IDs as what appear to be numbers (1 and 2 for the two achievements I've added); passing either "1" or the achievement name fails with "The parameter is incorrect."

Calling the following:
```js
xboxLiveContext.achievementService.getAchievementsForTitleIdAsync(
    xboxUserId,
    titleId,
    Microsoft.Xbox.Services.Achievements.AchievementType.all,
    false,
    Microsoft.Xbox.Services.Achievements.AchievementOrderBy.default,
    0,
    100)
```
succeeds with an empty list, so it appears the configured achievements in the dev center aren't accessible from the API.

It's taken literally 2 years for us to get to the point we can configure achievements since we first tried to get in touch with Microsoft, and we are at the point of Construct users on the ID@Xbox program having their contracts come up for expiry. Please help us get these features working!

**Comment by XboxLiveForum** [comment]
Hello, AshleyScirra.

Could you please provide the following information.
 
Required General Information

What platform is the issue happening on (XDK, or UWP)?
What XSAPI project flavor are they using (C++, WinRT)?
What XSAPI version are they using (1612, 1703, etc)?
What OS or XDK are they using? (XDK 1703, TH2, etc)
Additional Helpful Information

What error code was encountered?
Perhaps a fiddler trace where possible?

Once we have these details, we might have a better idea of which direction to take this investigation.
Please let us know.

Thanks!

**Comment by AshleyScirra** [comment]
Tried updating target SDK to 10.0.16299.0, still not working.

**Comment by AshleyScirra** [comment]
I created a submission in my sandbox and got it published. Still not working.

The dev center is still listing the type as an "App" rather than a "Game", even though I've chosen "Games" for the category. Could that be related somehow? How do you change the type of an app?

**Comment by jasonsandlin** [comment]
That's unlikely it.  A fiddler trace would be good to trace down what's going on. 

https://docs.microsoft.com/en-us/windows/uwp/xbox-live/using-xbox-live/troubleshooting/how-to-set-up-fiddler-for-debugging

**Comment by XboxLiveForum** [comment]
Hi Ashley,
I have a quick question for you. Is your title an ID title or Creator's Program title?

**Comment by AshleyScirra** [comment]
It's supposed to be an ID title. I've been told by a Microsoft contact my title has been approved for ID (it's only for testing, no plans to publish) and my xboxservices.config file does not specify `XboxLiveCreatorsTitle`. Is there anything else I need to do to make it an ID title? I suppose I could have missed something!

**Comment by XboxLiveForum** [comment]
Your Microsoft contact/DAM can help you make sure the title is configured correctly for ID. I recommend reaching out to them if you are in unsure.

**Comment by AshleyScirra** [comment]
I've got a fiddler trace, is it OK to share publicly or should I email it to someone?

I've also tried checking the Xbox Live config steps in the documentation, and updating to VS2017 and the lastest Windows SDK version (16299), still no luck.

**Comment by jasonsandlin** [comment]
Email it to jasonsa@microsoft.com

**Comment by AshleyScirra** [comment]
Resolved by email, thanks @jasonsandlin
