### ISSUE TITLE
social_manager doesn't signal event when user changes online status

### ISSUE THREAD

**Issue by daniuk-microsoft** [Microsoft/xbox-live-api#350]
Repro:
- Use an XBL enabled app (eg. Xbox One home app) to change a remote XBL user's "Appear" status from "Appear Online" to "Appear Offline"

Expected:
- The social_manager (which has that user in a social_group) should signal an event that the given user has gone offline.

Observed:
- No events are signaled by the social_manager for this user.

This is true for both going from "offline" to "online" as well.

Also, it appears that the library is getting the notification of the status change. In fiddler, I can see these requests go out when toggling "Appear" back and forth on the remote user:
GET https://peoplehub.xboxlive.com/users/xuid(<snipped xuid>)/people/xuids(<snipped xuid>)/decoration/detail,follower,preferredColor,avatar?cacheBuster=4

```
{"people":[{"xuid":"<snipped xuid>",
...
"isCloaked":true,
...}
```
 

GET https://peoplehub.xboxlive.com/users/xuid(<snipped xuid>)/people/xuids(<snipped xuid>)/decoration/detail,follower,preferredColor,avatar?cacheBuster=5

```
{"people":[{"xuid":"<snipped xuid>",
...
"isCloaked":false,
...}
```

**Comment by XboxLiveForum** [comment]
Hello, daniuk-microsoft.

Could you please provide the following information.
 
Required General Information

What platform is the issue happening on (XDK, or UWP)?
What XSAPI project flavor are they using (C++, WinRT)?
What XSAPI version are they using (1612, 1703, etc)?
What OS or XDK are they using? (XDK 1703, TH2, etc)
Additional Helpful Information

What error code was encountered?
Perhaps a fiddler trace where possible?

Once we have these details, we might have a better idea of which direction to take this investigation.
Please let us know.

Thanks!

**Comment by rakhad** [comment]
Can you try repoing the issue using the [Social sample](https://github.com/Microsoft/xbox-live-samples/tree/master/Samples/ID%40XboxSDK/Social/UWP/Cpp) found in our [samples repo](https://github.com/Microsoft/xbox-live-samples)? That sample currently targets 1711 and when I change a users presence, by toggling appear offline/online, I get the correct presence_changed event from social manager's do_work. Please let me know if this is not the case for you.

**Comment by daniuk-microsoft** [comment]
Using the Social sample, I am also seeing the presence_changed event. Going back to our title, I notice 2 things:

·         The event for the user’s presence change seems to take a very long time to arrive. In my testing I’m seeing delays of 7 to 20 minutes. Is this expected?

·          The reason we didn’t notice the event in our title is because we’re filtering users like so:

social_group->get_users_from_xbox_user_ids(event.users_affected());

                this returns an empty list if the affected users were removed from the group (and hence are indistinguishable from users who were not ever in the group).

It seems from the sample that the recommended implementation is to ignore users_affected() and instead iterate over social_group->users() for each social_group, for each event. Is this correct? I’ll have to do some more investigation, but this seems inefficient. At first glance, it seems like we need to cache a list of the users in each social_group so we can compare when users are added or removed from them. Is this recommended approach? Surely, this must duplicate work already being done by the social_manager.

Is it possible to get more direct notification when users are added or removed from social_groups?

Thanks again for your help.

D.

**Comment by rakhad** [comment]
This is a great point. Let me investigate what it would take to make this happen. Thanks for your patience.

**Comment by rakhad** [comment]
For now follow the pattern used by the social sample. I've added this feature request to our backlog and I'll update the thread when the feature is implemented.
