### ISSUE TITLE
cpprest dependency needs to be updated for NuGet package (fails to compile in latest VS)

### ISSUE THREAD

**Issue by aschultz** [Microsoft/xbox-live-api#357]
The latest VS 2017 compiler fails to build cppreset v2.9. The issue were fixed as of cpprest v2.10.1, but the library owners are no longer publishing to NuGet (suggesting use of vcpkg instead).

https://github.com/Microsoft/cpprestsdk/issues/655
https://github.com/Microsoft/cpprestsdk/commit/31b0e47b3a94c893b5cddd48af742cc911cd1cad
https://github.com/Microsoft/cpprestsdk/commit/05e474a2d8f041f56691a4e9f7f79bd0f110809c

**Comment by jasonsandlin** [comment]
Thanks for the intel.  We'll keep an eye out

**Comment by jasonsandlin** [comment]
Which VS 2017 compiler are you looking at that it fails for?  I'm using 15.6.7 and it seems to build fine.

**Comment by jasonsandlin** [comment]
Odd, it builds fine for us on that version of VS2017.  

How do I repro this issue?  Are you just building https://github.com/Microsoft/xbox-live-api/tree/master/Build/Microsoft.Xbox.Services.140.UWP.Cpp by itself with no edits and it errors for you?

I thought VS wouldn't break existing code

**Comment by jasonsandlin** [comment]
Should be fixed now
