### ISSUE TITLE
Xbox Live SDK 1612 switch_account() call stopped working

### ISSUE THREAD

**Issue by jorgegarciaMSE** [Microsoft/xbox-live-api#372]
Hi there,

We've been using the call to switch_account() for switching accounts in our game on Windows 10 until recently without problems. We are on Xbox Live SDK 1612 now and don't plan to update to latest version or use the account picker API, so ideally would like to keep what is already working.

After some debugging, it's observed that the result of the async operation to switch_account() returns success state with the same account that is already selected, but no UI window is shown in order to allow choosing a new user.

Could you please help?

Regards,
Jorge

**Comment by XboxLiveForum** [comment]
Hi Jorge,

We are going to need some additional information. Can you please provide the following:

				• What platform is the issue happening on (XDK, or UWP)?
				• What XSAPI project flavor are they using (C++, WinRT)?
				• What XSAPI version are they using (1612, 1703, etc)?
				• What OS or XDK are they using? (XDK 1703, TH2, etc)

Reproduction steps for the issue.

Kam - Xbox Live Forum Moderator

**Comment by jorgegarciaMSE** [comment]
Hi Kam,

Thanks for the quick response.

The issue happens in UWP application using the C++ XSAPI 1612 and Windows 10 OS version is 1709 (build 16299.371).

This is the code calls we are using (as I said, this used to work perfectly but no longer shows the UI for selecting a user):

`GetCurrentUserXboxLiveId(m_lastUserId);

coredispatcher->RunAsync(Windows::UI::Core::CoreDispatcherPriority::Normal,	ref new Windows::UI::Core::DispatchedHandler([this]()
	{
		SetPointerCapture(false);
		
		task<xbox::services::xbox_live_result<xbox::services::system::sign_in_result>> asyncOp = m_currentUser->switch_account(coredispatcher);
		create_task(asyncOp).then([this](xbox::services::xbox_live_result<xbox::services::system::sign_in_result> t)
		{
			
			SetPointerCapture(true);

			try
			{
				auto result = t.payload();
				if (result.status() == xbox::services::system::sign_in_status::success)
				{
					if (m_lastUserId[0] != 0)
					{
						GetCurrentUserXboxLiveId(idUserNew);
						if (strncmp(idUserNew, m_lastUserId, KUserPlatformIdSize) == 0)
						{
							return;
						}
					}
				}
				
				return;
			}
			catch (Platform::Exception ^e)
			{
				LogExceptionResult("cReqAppServerAccess::ReqAuthCodeOnEnter", e);
				
			}
		});
	}));
}`

Let me know if you need anything else.

Thanks,
Jorge

**Comment by XboxLiveForum** [comment]
Hi Jorge,

I am going to ask our team to investigate this further. We will let you know what we find once they complete their investigation. 

Kam - Xbox Live Forum Moderator

**Comment by jorgegarciaMSE** [comment]
Thanks Kam. 

Will be looking forward to hearing from you then.

Best,Jorge
