### ISSUE TITLE
Calling StatisticManager.AddLocalUser throws at line 105 in user_context_winrt.cpp 

### ISSUE THREAD

**Issue by Eversor** [Microsoft/xbox-live-api#415]
Code was working with the version from a few months ago. Updating the source throws this error in my games that were running before.

Here's the code on my end:

            var context = (ServiceProvider as XBoxLive_PlatformServiceProvider).context;
            var singleton = Microsoft.Xbox.Services.Statistics.Manager.StatisticManager.SingletonInstance;
            singleton.AddLocalUser(context.User);

I'm using the latest version of libHttpClient updated from source, if it is relevant.

**Comment by XboxLiveForum** [comment]
Hi Eversor,

Could you please provide the following information to help us investigate?
1. Which version of XSAPI are you using? (i.e. 1711, 1804, etc.)
2. Which engine are you using, if any?
3. Which IDE and version?
4. Is this for the Creators Program?
5. When you say you updated the source, are you referring to the libHttpClient source?

Thank you,

**Comment by Eversor** [comment]
1) Hello, i don't know where to get the XSAPI sorry... If it's the version of the Durango XDK inside the main folder i see a folder named 1703.
2) I'm using Monogame, a c# engine compatible with UWP. 
3) I'm using Visual Studio 2017, 15.6.6
4) ID@XBOX 
5) I'm up to date with the Git Repo, sorry for making things more confused.

**Comment by Eversor** [comment]
Testing further, i updated to 180400 and moved testing a simpler app:
running the SocialApp test in 
\xbox-live-api\Tests\CSharpTestApp\UWP\Social.140.sln
throws the same assert on SocialMediaManager.AddUser
![immagine](https://user-images.githubusercontent.com/733699/40229882-e9fff258-5a95-11e8-9283-8db8853348e5.png)

**Comment by XboxLiveForum** [comment]
Hi Eversor,
	
	We've created a service request for additional investigation. We will continue to update this thread as updates are available.
	
	We appreciate your patience in the meantime.
	
	Thank you,
	
Kam - Xbox Live Forum Moderator

**Comment by rakhad** [comment]
Fixed https://github.com/Microsoft/xbox-live-api/commit/adb1d7257f8b27c9a3ecae64982f1395b9eb5574
