### ISSUE TITLE
Trying to download Xbox-live-api nuget package fails from Visual Studio

### ISSUE THREAD

**Issue by Eversor** [Microsoft/xbox-live-api#416]
This is the third machine i try downloading the nuget package without success, so i thought i could add it here if someone knows how to go around the issue. 

	  CACHE https://www.nuget.org/api/v2/Packages(Id='Microsoft.Xbox.Live.SDK.WinRT.UWP',Version='2018.4.20180411.2')
	Restoring packages for C:\Repos\DoomAndDestiny\XNA4\Common\Universal\project.json...
	  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP'
	  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP' 759ms
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP/2018.4.20180411.2
	  OK https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP/2018.4.20180411.2 741ms
	  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Debug'
	  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release'
	  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug'
	  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Release'
	  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Debug' 282ms
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Debug/2018.4.20180411.2
	  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Release' 538ms
	  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release' 586ms
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Release/2018.4.20180411.2
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2
	  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug' 1016ms
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2
	  OK https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Debug/2018.4.20180411.2 943ms
	  OK https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Release/2018.4.20180411.2 1085ms
	Failed to download package 'Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release.2018.4.20180411.2' from 'https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2'.
	The HTTP request to 'GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2' has timed out after 100000ms.
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2
	Failed to download package 'Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug.2018.4.20180411.2' from 'https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2'.
	The HTTP request to 'GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2' has timed out after 100000ms.
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2
	Failed to download package 'Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release.2018.4.20180411.2' from 'https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2'.
	The HTTP request to 'GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2' has timed out after 100000ms.
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2
	Failed to download package 'Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug.2018.4.20180411.2' from 'https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2'.
	The HTTP request to 'GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2' has timed out after 100000ms.
	  GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2
	Failed to download package 'Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release.2018.4.20180411.2' from 'https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2'.
	The HTTP request to 'GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release/2018.4.20180411.2' has timed out after 100000ms.
	  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release'
	  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release' 244ms
	Failed to download package 'Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug.2018.4.20180411.2' from 'https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2'.
	The HTTP request to 'GET https://www.nuget.org/api/v2/package/Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug/2018.4.20180411.2' has timed out after 100000ms.
	  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug'
	  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release'
	  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release'
	The feed 'nuget.org [https://www.nuget.org/api/v2/]' lists package 'Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release.2018.4.20180411.2' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.
	  Unable to find package 'Microsoft.Xbox.Live.SDK.WinRT.UWP.Native.Release.2018.4.20180411.2'.
	Time Elapsed: 00:05:05.2435265
	========== Finished ==========

	  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug' 871ms
	  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug'
	  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Xbox.Live.SDK.WinRT.UWP.Netcore.Debug'

Connection speed is adsl 7mbps that is the standard connection speed in Italy. I suspect the package is so big that nuget has trouble downloading and times out while downloading.
To me this problem is strictly related to xbox-live-api as i never had any problems with other packages, even big ones as windows.core.sdk.

**Comment by XboxLiveForum** [comment]
Hi Eversor,
	
	We've created a service request for additional investigation. We will continue to update this thread as updates are available.
	
	We appreciate your patience in the meantime.
	
	Thank you,
	
Kam - Xbox Live Forum Moderator

**Comment by jasonsandlin** [comment]
Not much we can do about this.  Our PDBs are pretty big so they result in pretty large package sizes.  We're looking into ways to make smaller nuget packages but nothing concrete to announce yet.
