### ISSUE TITLE
Unhelpful StackOverflow exception if the XboxServices.config file is missing

### ISSUE THREAD

**Issue by Eversor** [Microsoft/xbox-live-api#418]
I was trying to build a sample app to demonstrate another issue, and run into this, think it should be fixed as it could get extremely frustrating if someone forgets to assign XboxServices.config to the project with Content and CopyIfNew properties set.

    The issue is happening on Windows 10, Debug mode targeted to x64 (Target 16299, MinVersion 10240)
    Microsoft.Xbox.Live.SDK.WinRT.UWP nuget package.
    Nuget package version is v2018.4.20180411.2 so i think it is version 1804
    I have installed XDK 1804 from https://developer.xboxlive.com/
    OS is Windows 10 build 16299
    IDE is Visual Studio Professional 2017 version 15.6.6

**Comment by jasonsandlin** [comment]
Hmm, it should fire a debug assert if its missing

**Comment by Eversor** [comment]
Seems like it only fires if Mixed Mode (or native ?) Debugging is selected. Shouldn't we see it in Managed mode as well?
