### ISSUE TITLE
Calling UpdateAchievementAsync throws an exception

### ISSUE THREAD

**Issue by pjcard** [Microsoft/xbox-live-api#425]
I've found that calling UpdateAchievementAsync with a value for percentComplete which matches the value the achievement already has on the backend returns a 304 (not modified), which makes perfect sense. However, the RT API is interpreting this as InvalidArgumentException.

This is making it hard to work with the API, as when running under the debugger we are getting first chance exceptions for any achievement we happen to have unlocked.

Here's some output from it happening. Here we call UpdateAchivementAsync with a percentComplete value of 100 when the value on the backend is already 100. This is from the Feb QFE 2 XDK:

 ```
001037|024612|000428| [XBOX SERVICE CALL] #1
 001037|024612|000428| [HTTP Method]: POST
 001037|024612|000428| [URI]: https://achievements.xboxlive.com/users/xuid(REDACTED)/achievements/REDACTED/update
 001037|024612|000428| [Request Headers]: Accept-Language: en-US,en; Content-Length: 182; Content-Type: application/json; charset=utf-8; User-Agent: XboxServicesAPI/2017.11.20171204.01; x-xbl-contract-version: 2; 
 001037|024612|000428| [Authorization Header]: XBL3.0 REDACTED
 001037|024612|000428| [Signature Header]: REDACTED
 001037|024612|000428| [Request Body]: {"achievements":[{"id":"3","percentComplete":100}],"action":"progressUpdate","serviceConfigId":"REDACTED","titleId":REDACTED,"userId":"REDACTED"}
 001037|024612|000428| [HTTP Status]: 304 [HTTP_E_STATUS_NOT_MODIFIED] 
 001037|024612|000428| [Response Headers]: Cache-Control: no-cache, no-store; Content-Length: 0; Date: Wed, 14 Mar 2018 17:51:52 GMT; Expires: -1; MS-CV: BPRRi/vf0EOfl1xJYojKkw.0; Pragma: no-cache; X-Content-Type-Options: nosniff; 
 001037|024612|000428| [Response Body]: ""
 Exception thrown at 0x000001065369390A in REDACTED.exe: Microsoft C++ exception: Platform::InvalidArgumentException ^ at memory location 0x000002077877F698. HRESULT:0x80070057
 
 Exception thrown at 0x000001065369390A in REDACTED.exe: Microsoft C++ exception: Platform::InvalidArgumentException ^ at memory location 0x00000207784EF510. HRESULT:0x80070057
 
 Exception thrown at 0x000001065369390A (kernelx.dll) in REDACTED.exe: 0xE06D7363: Microsoft C++ Exception (parameters: 0xCCCCCCCC19930520, 0x00000207784EEF10, 0x0000010658830AE0, 0x0000010658730000).
```

**Comment by pjcard** [comment]
Hi Jason, thank you for the reply. Regarding the choice of API you're correct, I don't want to go into details on a public forum, but as you guessed the C++ API is not currently an option for us.

Your suggestion would be great, it would definitely resolve the issue for us.

**Comment by Eversor** [comment]
Following up the API choice argument, is there any kind of documentation about differences and use cases of the 6 different nuget packages available?
![immagine](https://user-images.githubusercontent.com/733699/40411697-aba2d1fa-5e60-11e8-8d6d-7d0bfa2dfe26.png)

**Comment by jasonsandlin** [comment]
This is done: https://github.com/Microsoft/xbox-live-api/commit/a15b8c86d3b0d1bc9c0b9ada1bb0c898a7984c5a
