### ISSUE TITLE
Readme needs updated.

### ISSUE THREAD

**Issue by killa78** [Microsoft/xbox-live-api#483]
The link to the developer program overview (found at https://developer.microsoft.com/en-us/games/xbox/docs/xboxlive/get-started/developer-program-overview) is a 404.

**Comment by XboxLiveForum** [comment]
Thanks for letting us know, @killa78. We have created a service request to update the Readme. <p> In the meantime, here is the correct link to the developer program overview: [https://docs.microsoft.com/en-us/windows/uwp/xbox-live/developer-program-overview](url)

**Comment by jasonsandlin** [comment]
Thanks, fixed
