### ISSUE TITLE
Presence Filter Enumeration Has Inconsistent Values

### ISSUE THREAD

**Issue by pjcard** [microsoft/xbox-live-api#488]
The presence filter enumeration seems to be inconsistent in its values relating to players which have interacted with the title. The enumeration uses 'All' both to refer to 'both offline and online' and 'both having played the game or is playing the game', this seems to have left gaps in the enumeration, for instance there is no "Has played the game and is online or offline" or "Has played the game and is online", or at least that's how it appears. There is also no "has not played the game and is online" or "has not played the game and is offline".

Specifically, I need "Has played the game and is online" and "Has not played the game and is online", so that I can easily separate my friends list into "Online playing the title", "Online has played the title" and "online has not played the title", so that in our limited UI, we always prefer more optimal friends.

I wonder if this filter would be better exposed as a bitfield. (online|offline, has played|has not played, is playing|is not playing).

https://github.com/Microsoft/xbox-live-api/blob/c38e851750491a2e68c2867080204a4706b5a15f/Source/Services/Social/WinRT/PresenceFilter_WinRT.h

**Comment by rakhad** [comment]
Closing due to lack of update.

**Comment by rakhad** [comment]
To get the To get the "Online playing the title" list you can use presence_filter::title_online
To get the "Online has not played the title" list you can use presence_filter::all_online - presence_filter::all_title
To get the "Online has played the title" list you can use presence_filter::all_online - "Online has not played the title"

**Comment by pjcard** [comment]
Yeah, that's one workaround, we went with just using PresenceFilter::AllOnline and accepting that people with more friends than could fit in the group would potentially have the wrong ones in their friends lists.

Shame its still an issue in the GDK.
