### ISSUE TITLE
[UWP] Crash after removing current user from system

### ISSUE THREAD

**Issue by sylwek** [Microsoft/xbox-live-api#497]
Hi,

I have encounter a crash on 1806 QFE and 1806 release versions of Xbox Live API both in my app as well as in the Xbox Live samples after removing user from system.
I was able to invoke crash both in Leaderboards 2017 sample ( [LINK](https://github.com/Microsoft/xbox-live-samples/tree/master/Samples/CreatorsSDK/Leaderboards/UWP/Cpp) ) and Game Save sample ( [LINK](https://aka.ms/atgsplGameSave) ) with the newest version of Xbox Live API from nuget.

Callstack:
![obraz](https://user-images.githubusercontent.com/5664229/44254806-39e9e980-a204-11e8-8f96-21fd3ea9aa0d.png)

![obraz](https://user-images.githubusercontent.com/5664229/44254874-6dc50f00-a204-11e8-88c0-ccf6dea4b356.png)

**Affected versions**: 
- 1806 QFE 
- 1806

**Platform**: UWP

**Repro steps**:
1. Run app
2. Sign in to Xbox Live
3. Minimalize app
4. Go to Settings -> Accounts -> Email & app accounts and remove user that was signed in within the app
5. Get back to app and perform the action that will call Xbox Live API code

**Expected Behaviour**: Xbox Live API code would not crash and sign out completed handler will be invoked

**Comment by XboxLiveForum** [comment]
Hi Sylwek,

I have created a VSO ticket on this issue. Your ticket no. is 18710131


Muhammad Ikram
XDP Help

**Comment by jasonsandlin** [comment]
We fixed the crash, but this is not a supported way to remove a user on UWP.  To sign out a user, use the Xbox app.
