### ISSUE TITLE
Error 0x8015DC0B on PC App for Ukraine region

### ISSUE THREAD

**Issue by kryvyifedir** [Microsoft/xbox-live-api#501]
Error 0x8015DC0B occurs in Ukrainian region whenever user tries to open Xbox App on a PC

**Comment by jasonsandlin** [comment]
We can't provide user support here or we'd get overwhelmed.  Please use https://answers.microsoft.com/en-us/xbox/forum.  I know the Xbox team is watching those forums and responding.
