### ISSUE TITLE
GetForUserAsync not return and no exception

### ISSUE THREAD

**Issue by MakotoHasegawaBKK** [Microsoft/xbox-live-api#510]
I using 1806 QFE Release.
When popup notfinish synchronize dialog then close application on PC.
Look at Task Manager still have a Xbox Game UI.  I think this is controll the dialog.
Launch application again and call GetForUserAsync but not retuan and no exception, can not continue game.
Same kind of issue has a XboxOne in case occur exception on PickSingleUserAsync.
but i can slove catch exception and retry again PickSingleUserAsync untill close the dialog.

I want try new release but 1807 Release is looks like a 1804.
Please check this link.
https://github.com/Microsoft/xbox-live-api/releases

Best

**Comment by MakotoHasegawaBKK** [comment]
I have update.

I build mini version 10.0.10240, so this is quire low version.
In case close synchronize dialog whth my application. but still have Xbox Game UI task.
I change mini version 10.0. 16299 in case not close synchronize dialog with my application.
I launch application again then click the dialog synchronize GetForUserAsync  return success.
Sorry my mistake.

Please check only 1807 Release link.
Best.

**Comment by jasonsandlin** [comment]
Which release are you using?  We encountered instability with our 1806 QFE 3 and prior releases, so recalled them and rolled back to make our 1807 release the same as our stable 1804 release.  

When calling WinRT APIs be sure to follow proper error handling: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/using-xbox-live/error-handling/error-handling-winrt

**Comment by MakotoHasegawaBKK** [comment]
I using 1806 QFE (sorry i don,t know last number. maybe when i download this version doesn't have a number)

I used 1804 before but 1804 has othe problem.
1804 crush application when offline internet.
So i update 1806 QFE then not occur offline crash issue.

And i doing error handling sure, I can catch other exception.
This issue looks like infinity looping in GetForUserAsync.
I think GetForUserAsync try to show dialog but couldn't, because already running Xbox Game UI process.
if you stop application from Visual studio debugger stop button doesn't have a problem because Xbox Game UI can finish process.
This problem have launch application directry then close application from taskbar application icon. Xbox Game UI still running.

Our application multi user signin, i set multiple setting to manifest but i don't know this is relative this issue. <uap:SupportedUsers>multiple</uap:SupportedUsers>

I will try to check this problem by 1804 
but i don't know how to slove 1804 offline crash issue.

**Comment by jasonsandlin** [comment]
Can you verify you see the an offline crash with 1804 and give details about exactly what's going when it crashes including callstack?

**Comment by MakotoHasegawaBKK** [comment]
When i try offline crash problem close debugger too, i couldn't get call stack.
But i try again. sorry but can do tomorrow.

**Comment by jasonsandlin** [comment]
Thanks.  If you could tell us how to reproduce the issue with a sample at https://github.com/Microsoft/xbox-live-samples that'd be verify helpful.

**Comment by MakotoHasegawaBKK** [comment]
Sorry late reply.
I checked 1807, this is not clash when offline.
But this posted title issue still have.
I could reproduce on sample project.
I make new post with attatch screen shot.

https://forums.xboxlive.com/questions/85348/uwp-getforuserasync-not-return-and-no-exception-on.html
