### ISSUE TITLE
Bulk Update Achievements

### ISSUE THREAD

**Issue by GarethPikPok** [microsoft/xbox-live-api#511]
We are looking into some rate limiting issues, and we noticed that the Fiddler traces for achievements take an array of achievements: {"achievements":[{"id":"42","percentComplete":100}],"action":"progressUpdate","serviceConfigId":"-----","titleId":-----,"userId":"-----"}

However, there is no method in the XboxLive SDK to utilize this. This means that we have to send 6 service requests instead of just 1 when we complete some in game activities that achievements are linked to.

XDK Version 180200 (Microsoft::Xbox::Services::Achievements::AchievementService)
UpdateAchievementAsync (In Platform::String^ xboxUserId, In Platform::String^ achievementId, In uint32 percentComplete)
UpdateAchievementAsync (In Platform::String^ xboxUserId, In uint32 titleId, In Platform::String^ serviceConfigurationId, In Platform::String^ achievementId, In uint32 percentComplete)

No method allows multiple achievements to be passed. Is this intentional? We feel a method to allow a bulk operation would be beneficial.

**Comment by jasonsandlin** [comment]
Thanks for the feedback.  We'll try to get this feature request into a future release

**Comment by rakhad** [comment]
We're tracking this as an improvement in the GDK.
