### ISSUE TITLE
Help please. Time leaderboards.

### ISSUE THREAD

**Issue by madcowie** [Microsoft/xbox-live-api#515]
I can find very little information on this subject. How do you go about sending a time to a leaderboard? I was thinking it would be easier to send an int and then hopefully the leaderboard convert the int into a time?

So far if I send for example 250000 as an int. On my Sandbox leaderboard it just posts 250,000 rather than that value as a time.

Does a an Xbox in Dev Mode with the correct sandbox attached show an entry as a time on a leaderboard?

Also my game will have 18 leaderboards. Will I have 18 prefab leaderboards in one scene or am I missing something here.

**Comment by rakhad** [comment]
Today we don't convert the int to time for you. You can do this for your game by editing the LeaderboardEntry.cs script to format the value in a way that makes sense for your game.

You can use a single leaderboard prefab and change Leaderboard.cs' Stat variable and call Refresh() whenever you want to change which stat is rendered.
