### ISSUE TITLE
Claiming gamertag!

### ISSUE THREAD

**Issue by ronnielivingsince1994** [microsoft/xbox-live-api#521]
Hi Microsoft team,

I'm trying to define the claime gamertag functionality in python based on the cpp logic from https://github.com/blgrossMS-zz/xbox-live-api/blob/17c586336e11f0fa3a2a3f3acd665b18c5487b24/Source/System/iOS/XboxSignInUI/Bridge/XboxProviderBridge.cpp

This is the my piece >>

#After creating, XboxLiveClient object I'm calling this sequence from the main function>>

headers = xbl_client.session.headers #for cookie management
xuid =  auth_mgr.userinfo.xuid
output = xbl_client.profile.change_gamertag(headers, xuid, 'somerandomgamertag')
print(output.status_code) #returns 403 
print(output.content) # returns b'{"source":"Accounts","code":5025,"description":"272abc3c-8b49-469f-b589-72eaa902fa64","data":null,"traceInformation":null}'

#Here is the definition of change_gamertag>>

def change_gamertag(self, headers, xuid, target_gamertag):
        url = "https://accounts.xboxlive.com/users/current/profile/gamertag" 
        headers.update(self.HEADERS_PROFILE) #HEADERS_PROFILE = {'x-xbl-contract-version': '1'}
        post_data= {
              "Gamertag" : target_gamertag,
              "ReservationId":  xuid 
        } 

        return self.client.session.post(url, headers=headers,  json = post_data)

Please help me understand what is being missed in this post request?

Let me know, if more details are required.

Thanks!

**Comment by jasonsandlin** [comment]
Sorry this isn't a supported scenario

**Comment by ronnielivingsince1994** [comment]
Hey jason,

I understand that. I worked it out though. 
My bad, I should had closed this issue.

**Comment by zapz12** [comment]
How did you fix it?

**Comment by zapz12** [comment]
> Hey jason,
> 
> I understand that. I worked it out though.
> My bad, I should had closed this issue.

^^
