### ISSUE TITLE
Erroneous use of `Null` enum where `null()` value should be used.

### ISSUE THREAD

**Issue by scztt** [microsoft/xbox-live-api#525]
https://github.com/microsoft/xbox-live-api/blob/30671e3d0cf1495c0be6947ff9469600f47a48d1/Source/Services/EntertainmentProfile/entertainment_profile_list_xbox_one_pins.cpp#L168

https://github.com/microsoft/xbox-live-api/blob/30671e3d0cf1495c0be6947ff9469600f47a48d1/Source/Services/EntertainmentProfile/entertainment_profile_list_xbox_one_pins.cpp#L121

`web::json::value::Null` is an enumerator denoting the `Null` JSON type - the enumerators value is 5: https://github.com/microsoft/cpprestsdk/blob/bed8fa538c862a8297cb02c99d8b3dcc29247d5b/Release/include/cpprest/json.h#L91

In the above two cases (and likely others in the codebase) this 5 is being converted to a valid JSON `Number` value, rather than to a `Null`.

**Comment by jasonsandlin** [comment]
Thanks for spotting this bug
