### ISSUE TITLE
create_game_from_lobby null pointer access exception

### ISSUE THREAD

**Issue by ag-rutger** [microsoft/xbox-live-api#527]
We ran into a crash in create_game_from_lobby, very similar to issues 88656 and 85479 on the xbox one development forum.

Looking at the crash I see that sessionToCommitCopy on line 960 is null (which is where it crashed). The commitResult error is 412 and null payload. As the lobby only has 1 session property (joinable_by_friends) and doesn't have c_transferHandlePropertyName which means is_transfer_handle_state would have returned false, the empty payload was assigned to sessionToCommitCopy which resulted in this crash.

Adding a null check to the while statement will probably prevent this crash, but I'm not sure if this is the proper fix.

**Comment by jasonsandlin** [comment]
Thanks for the bug report

**Comment by ag-rutger** [comment]
For completeness, we ran into an issue with a microsoft provided version (See dev forum 92324, NDA). I did not try it with source where commit b5d3a5f3ccd7567e1a915f4759c74f61164ee947 might had already fixed the issue. To be safe, we'll be using source with the nullptr check.

**Comment by rakhad** [comment]
Closing since post references a potential fix. If this issue is still happening please reactivate.
