### ISSUE TITLE
Where do I set events on Partner Center (2017 title) to use in writeEvent?

### ISSUE THREAD

**Issue by georgii11** [microsoft/xbox-live-api#529]
Hi,

I am trying to use _m_xboxContext->events_service().write_in_game_event(eventName);_ to update a leaderboard score, however I am not sure what I should sent for the event name.
Where do I configure the events in Partner Center for a 2017 title?

Thanks!

**Comment by jasonsandlin** [comment]
You can name as you like without configuring first.  The only thing you need to configure is which of those stats you want to become featured stats which are advertised to other users.
