### ISSUE TITLE
Nuget Error

### ISSUE THREAD

**Issue by brunotrevisan** [microsoft/xbox-live-api#530]
Microsoft.Xbox.Live.SDK.WinRT.UWP  fail to install :/

**Comment by ET3D-ET3D** [comment]
The problem might be with nuget disliking your PATH. That's a problem with newer nuget versions. I'm not sure this affects the built-in nuget, but when I had a problem with this, I tried command line nuget, it failed, and then I found that my PATH had an empty component (;;), and removing that solved the problem. Anything in the PATH which doesn't translate directly to a working directory will cause nuget to fail.

I hope this helps.

**Comment by rakhad** [comment]
Closing since there has been no movement on this issue. Please reactivate if this is still an issue.
