### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by TheBlackPlague** [microsoft/xbox-live-api#532]
It seems there is no clear documentation for how to use the XSAPI using .NET Core.

The WinRT API for UWP requires use of `Windows.Xbox.Services`. For unknown reasons (probably lack of the package in .NET Core), I've been unable to access this package.

**Comment by TheBlackPlague** [comment]
No longer necessary.

**Comment by CartBlanche** [comment]
@TheBlackPlague How did you get this working? I'm also interested in using the API via .NET.
