### ISSUE TITLE
Async calls never returning

### ISSUE THREAD

**Issue by ThoriumThor** [microsoft/xbox-live-api#533]
Hello, we have a game on the Windows Store and are getting several user complains / day that their game is unable to sync to their connected storage.  After looking at their log files, we've seen a variety of issues, but most appear to be one or more async calls in Microsoft.Xbox.Services.dll just never returning.

The first such example we looked at, the user was able to sign in but then would get stuck on a call to GetForUserAsync() indefinitely (or at least for 5+ minutes).  The next case we looked at, the log indicated that the user had never received a return result from their initial call to SignInAsync().  Our code is designed to deal with a failed result from each of these calls, but assumes that they will return something at all in a reasonable amount of time.

I've seen other users with similar issues around the internet (like on the Creator's Program variant of this page and the Microsoft Win10 support forums), but never with a satisfactory resolution.

Our project is built as a UWP app on .NET4.x and IL2CPP.  We're on Unity 2018.4.22f1 and the 1807 release of this library.

Thanks for any help or workarounds you can provide!

**Comment by l-raze** [comment]
Hi @ThoriumThor 

Thanks for reaching out. I was wondering if you are an id@Xbox developer, or a creators developer?

**Comment by ThoriumThor** [comment]
Hello, I am an id@xbox developer.

**Comment by l-raze** [comment]
Hi @ThoriumThor, since you are an id@xbox developer, would you please ask this question on the id@xbox developer forums so we can best support you with this issue.

**Comment by ThoriumThor** [comment]
Hi @l-raze , sorry for the delay.  Do you have a link to the id@xbox developer forums?  I'm only aware of the Xbox Developer Forums.  I've already posted this issue there but it died with no resolution. https://forums.xboxlive.com/questions/107418/getforuserasync-not-returning.html

We recently had a breakthrough in our understanding of this issue.  It seems related to Windows Services, in particular the Xbox Live Auth Manager and Xbox Live Game Save services.  We've advised a few users with this issue to manually restart these services and have confirmed that it fixes the issue.

It seems like there is some fail state that these services can get in such that they do not correctly start up when our application calls into the XBL API, which in turn causes Async() calls to simply never return.

Can you provide any insight into this and if so, can you advise me on the best place that we can discuss?  Thank you!

**Comment by jasonsandlin** [comment]
https://forums.xboxlive.com/ is the right spot.  Only ID@Xbox developers can access it.  Start a new thread with details if there's an outstanding issue.  Thanks
