### ISSUE TITLE
[Leaderboards] Leaderboards Completes and ErrorCode is 0. but Exception thrown when accessing statisticEvent.EventArgs

### ISSUE THREAD

**Issue by CartBlanche** [microsoft/xbox-live-api#548]
I'm using the following C# code to process leaderboards entries...

```
	case StatisticEventType.GetLeaderboardComplete:
	        if(statisticEvent.ErrorCode == 0)
	        {
		        try
		        {
			        if (statisticEvent.EventArgs is LeaderboardResultEventArgs leaderboardREsultEventArgs)
			        {
				        var leaderboardResult = leaderboardResultEventArgs.Result;
				        foreach (LeaderboardRow leaderRow in leaderboardResult.Rows)
				        {
					        Debug.WriteLine(string.Format("Rank: {0} | Gamertag: {1} | {2}:{3}\n\n", leaderRow.Rank, leaderRow.Gamertag, "test", leaderRow.Values[0]));
				        }
			        }
		        }
		        catch (Exception ex)
		        {
			        Debug.WriteLine(string.Format("Error: {0}", ex.Message));
		        }
	        }
	        break;
```

But an exception is always thrown, even though ErrorCode is 0. 
I'm using a purely English Windows OS and the error message come back in Spanish as **No encontrado (404)**.

I'm using the 2018.6.20181010.2 nuget package, if that makes any difference.

Any suggestions on what I should look into to track this down why seems to be crashing? Any other information you require?

**Comment by CartBlanche** [comment]
For those wondering why this happened for me, is that the `XboxServices.config` files incorrectly had `XboxLiveCreatorsTitles` set to `true`, when it should have been false. So that allows you to successfully login, but then it fails. I now have another issue related to logging in, when `XboxLiveCreatorsTitle` is false, but I won't hassle this issue with that.

**Comment by CartBlanche** [comment]
May I suggest a more useful error message is thrown that "Not found 404", which really is misleading. Maybe suggest to the user that they check their `XboxServices.config` file, for example. I waster 3 days before I realised it was related to that true/false flag.

**Comment by CartBlanche** [comment]
I re-opened this because it is still and issue. It seems the exception is happening via the COM interop during the EvenArgs call.

**Comment by CartBlanche** [comment]
@jplafonta Any ideas?

**Comment by jasonsandlin** [comment]
When the service returns 404 here, it means the leaderboard wasn't found.  Are you making a Creators title?  Did you try creating a new creating a new stat/leaderboard in Partner Center and then click Publish?  This doc page should explain the steps in more detail:

https://docs.microsoft.com/en-us/gaming/xbox-live/features/player-data/stats-leaderboards/title-managed/config/live-tm-leaderboards-portal

**Comment by CartBlanche** [comment]
@jasonsandlin Thanks for replying. Yes it is a Creator Title. 
my XboxServices.config file is set to 
```
....
"TitleId": 1782596884,
"XboxLiveCreatorsTitle": true
```

I assume if I were to set it to **false**, then it means I'm part of the ID@Xbox programme?

Whyis the service throwing a 404 exception message, but `statisticEvent.ErrorCode == 0`? Shouldn't the ErrorCode be something other than 0 and the `statisticEvent.ErrorMessage` should have a sensible message, at this point, for an obvious error like "Not found"? 

I have had all the leaderboards setup for months now (while not being able to use them), as per this screenshot...
![Leaderboards](https://user-images.githubusercontent.com/271363/112728676-5607a880-8f20-11eb-9526-7c4e08deeb1e.png)

Where is the **Publish** button  that you mention above? All I see is a **Test** button. Which is only for publishing to the Sandbox, isn't it?
Even after putting my PC into the Sandbox mode
![Sandbox](https://user-images.githubusercontent.com/271363/112729152-a849c900-8f22-11eb-8be5-b9b9e5c112a5.png)

I still get exactly the same error message on my Windows PC. So neither **Sandbox** mode or **Retail** mode work for me, at the moment, but the Xbox Live Login works, as I get back a valid User object.

I really would like to get this working as my game is already in the Windows Store (couldn't wait anymore) and I've had to put a message saying that Leaderboards are coming.

**Comment by jasonsandlin** [comment]
Yes, XboxLiveCreatorsTitle = false means published by ID@Xbox or published by a Microsoft Partner.

The "Test" button will publish the changes to the sandbox.  When you ship the title, shipping process will copy the settings from the sandbox to Retail.

Be aware of this if you are working on a Creator's title:
https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live
