### ISSUE TITLE
XblPresenceSetPresenceAsync is causing XTaskQueueDispatch to trigger time sensitive thread warning

### ISSUE THREAD

**Issue by Himanshu-Chablani** [microsoft/xbox-live-api#549]
Hi,

We recently turned on time sensitive thread warnings for our main thread and noticed that XTaskQueueDispatch was triggering a warning when dispatching the callback for XblPresenceSetPresenceAsync. We added question about it on the xboxlive forums (https://forums.xboxlive.com/questions/113469/index.html) and they suggested we create an issue here. 
According to them :
>it looks like this bug is due to the HTTP library scheduling some of the background work on the completion port. This function shouldn't be getting called when you call dispatch on the completion port.

Best regards,
Himanshu Chablani

**Comment by jasonsandlin** [comment]
This old issue should have been fixed a while back.  The XAsync completion port API was fixed to not trigger time sensitive warnings
