### ISSUE TITLE
Visual Studio 2019 hanging when adding xsapi.staticlib.props file

### ISSUE THREAD

**Issue by msnancyzhang** [microsoft/xbox-live-api#558]
I was following the instructions of linking xsapi source code in our game solution, but VS became not responding (forever) when I tried to add the props file.

I was running as administrator and had disabled extensions when I saw some suggestions online, but didn't help.

**Comment by jasonsandlin** [comment]
Hmm, that's odd.  You could try manually added this line to your vcxproj:
  <Import Project="..\xsapi.staticlib.props" />
Just adjust the path to it where it lives.  Its what our test apps use, so it should work.  Feel free to reopen if you are stuck
