### ISSUE TITLE
Results from inventory API are always empty

### ISSUE THREAD

**Issue by podhornyi96** [microsoft/xbox-live-api#559]
I'm trying to fetch account games from xbox live using inventory endpoint - https://docs.microsoft.com/en-us/gaming/xbox-live/api-ref/xbox-live-rest/uri/marketplace/uri-inventoryget, but always receive empty results:

![image](https://user-images.githubusercontent.com/10508355/110992114-27b19700-837e-11eb-8fa5-bbac422d6d4c.png)

**Comment by jasonsandlin** [comment]
Are you an ID@Xbox developer?  This API only for games that want to fetch the user's marketplace items for that game (eg how many gold coins the player bought, etc)

**Comment by podhornyi96** [comment]
@jasonsandlin I'm not ID@Xbox developer. I've registered new application in Azure AD using account type "**Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)**". If I understood correctly its not possible to retrieve games from account using inventory endpoint?

**Comment by jasonsandlin** [comment]
That's right.  This isn't exposed AFAIK -- at least not through Xbox Live.

**Comment by podhornyi96** [comment]
@jasonsandlin Is there any way to retrieve xbox live account games?

**Comment by jasonsandlin** [comment]
Not as far as I know but the best place for Windows Store SDK related questions is https://social.msdn.microsoft.com/Forums/windowsapps/en-US/home?forum=dcefi

**Comment by podhornyi96** [comment]
@jasonsandlin Thank you for your help
