### ISSUE TITLE
Nuget package hasn't been updated since 2018, will it be updated soon?

### ISSUE THREAD

**Issue by CartBlanche** [microsoft/xbox-live-api#561]
The Xbox.Live.SDK.UWP nuget package hasn't been updated in 3 years. Is it likely to be updated any time soon, or has Microsoft dropped support for UWP apps?

**Comment by CartBlanche** [comment]
@jplafonta Will this be addressed at some point?

**Comment by jasonsandlin** [comment]
UWP is still supported and 2018.6.* UWP nuget package is the latest that UWP titles are shipping with

**Comment by CartBlanche** [comment]
@jplafonta That is great to hear. Do Microsoft provide any C#/.NET sample projects that show it all working? I tried compiling the C++ sample projects in VS2019 and it wouldn't even build and has 47 errors, so I couldn't test it using that either.

**Comment by CartBlanche** [comment]
@jplafonta the other issue with this old nuget is that it doesn't support ARM64 devices natively. These nugets only contain ARM support, AFAICT.

**Comment by jasonsandlin** [comment]
That's right, ARM64 isn't supported in these UWP nugets.  

Be aware of this if you are working on a Creator's title: 
https://github.com/microsoft/xbox-live-unity-plugin#2021-update-more-accessible-creators-program-no-longer-requires-xbox-live

**Comment by CartBlanche** [comment]
@jasonsandlin what about C# samples showing best practices for using the nugets??
