### ISSUE TITLE
Fetching a list of owned games for a user

### ISSUE THREAD

**Issue by s0r3-glitch** [microsoft/xbox-live-api#575]
I am attempting to use the Xbox live API to obtain a list of games owned by a user, however, it appears that I need an XSTS in order to make calls to the inventory service. Is there another way I can go about making calls to the inventory service without the need for an XSTS, or is there another there a different URL I can use to make these request? Thanks

**Comment by jasonsandlin** [comment]
Yes you need to use XSTS to call the inventory service.
