### ISSUE TITLE
A Simple Guide For Newbies

### ISSUE THREAD

**Issue by tayannastudios** [microsoft/xbox-live-api#596]
I'm an id@xbox user and am publishing via UWP (Can't afford the Unity Pro Licence to go with XGDK).

I'm at an absolute loss on how to implement the achievements 2017 system within Unity. I can't find one logical explanation online at all.

Does anyone know, in the most simplistic way possible, how to implement the coding for achievements? They're all set up in the Managed Partners section, I just need to code. I'm a TOTAL newbie with code.

Thanks in advance for any help.

**Comment by jasonsandlin** [comment]
Where did you see that Unity Pro is required for GDK?  

GDK PC for Unity can be done following instructions here: 
https://github.com/microsoft/gdk-unity-package#supported-versions-of-unity
and will put you on a much easier path

**Comment by tayannastudios** [comment]
For GDK Xbox releases it requires a Unity Pro licence now if you're
deploying in Unity.

**Comment by jasonsandlin** [comment]
Understood.  I recommend you contact ID@Xbox support which can give further guidance
