### ISSUE TITLE
xsapi.staticlib.props missing in NuGet package Microsoft.Xbox.Live.SDK.Cpp.UWP 2017.3.20170228.1

### ISSUE THREAD

**Issue by MrZweistein** [Microsoft/xbox-live-api#97]
The file "xsapi.staticlib.props" is missing in the NuGet package Microsoft.Xbox.Live.SDK.Cpp.UWP 2017.3.20170228.1 so you cannot finish the last steps as described there: 
[Adding Xbox Live APIs binary package to your UWP project](https://developer.microsoft.com/en-us/games/xbox/docs/xboxlive/get-started/uwp/adding-xbox-live-apis-binary-package-to-your-uwp-project)

**Comment by jasonsandlin** [comment]
That's a doc bug.  You can safely ignore this step.  Thanks for reporting

**Comment by MrZweistein** [comment]
Thanks. 

On a side note: Are there any plans to release a similar package for normal C# Windows 10 Universal projects (not Unity based)?

**Comment by jasonsandlin** [comment]
We'll look into this.  You can try linking to the source here https://github.com/Microsoft/xbox-live-api-csharp but we haven't flushed this path out or created NuGet packages.  If you run into blockers, feel free to open them at https://github.com/Microsoft/xbox-live-api-csharp/issues

**Comment by MrZweistein** [comment]
Thanks. I will wait for an official release ;)
